services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - service1
      - service2

  service1:
    image: service1
    ports:
      - "8080:8080"

  service2:
    image: service2
    ports:
      - "8000:8000"