apiVersion: v1
kind: Service
metadata:
  name: rust-app
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 8000
  selector:
    app: rust-app
