name: Deploy Docker Compose to Azure WebApp
on:
  push:
    paths:
      - "nginx/**"
      - "webapp1/**"
      - "webapp2/**"
      - "docker-compose-prod.yml"
      - ".github/workflows/DeployWebapp1Azure.yml"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Using Azure webapp publish profile for authentication
      - name: Download Web App publish profile
        id: publishprofile
        uses: azure/action-download-publish-profile@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: "production"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push NGINX image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/nginx:latest

      - name: Build and push Service1 image
        uses: docker/build-push-action@v4
        with:
          context: ./webapp1
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/service1:latest

      - name: Build and push Service2 image
        uses: docker/build-push-action@v4
        with:
          context: ./webapp2
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/service2:latest

      - name: Generate production docker-compose file
        run: |
          cat > docker-compose-prod.yml << EOF
          version: '3'
          services:
            nginx:
              image: ${{ secrets.ACR_LOGIN_SERVER }}/nginx:latest
              ports:
                - "80:80"
                - "443:443"
              depends_on:
                - service1
                - service2
            service1:
              image: ${{ secrets.ACR_LOGIN_SERVER }}/service1:latest
              expose:
                - "8080"
            service2:
              image: ${{ secrets.ACR_LOGIN_SERVER }}/service2:latest
              expose:
                - "8000"
          EOF

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ steps.publishprofile.outputs.publishProfileContent }}
          configuration-file: docker-compose-prod.yml
          type: compose
