# name: Deploy Webapp1 on AWS

# on:
#   push:
#     paths:
#       - "webapp1/**"
#     branches:
#       - main

# env:
#   AWS_REGION: us-east-1
#   AWS_ACCOUNT_ID: your-account-id
#   DOCKER_IMAGE_NAME: your-docker-image-name
#   CLOUDFRONT_DISTRIBUTION_ID: your-cloudfront-distribution-id
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   ECR_REGISTRY: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup QEMU for arm64
#         if: runner.os == 'Linux'
#         run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

#       - name: Setup Docker for arm64
#         uses: docker/setup-qemu-action@v2
#         with:
#           platforms: linux/arm64

#       - name: Setup Docker buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Login to Amazon ECR
#         run: |
#           aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
#           docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

#       - name: Build and push Docker image
#         run: |
#           cd webapp1
#           docker buildx create --use
#           docker buildx build --platform linux/arm64 \
#             -t ${{ env.ECR_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest \
#             --push .

#       - name: Deploy to AWS ECS
#         uses: imehedi/action-awscli-v2@latest
#         with:
#           args: >
#             aws ecs update-service
#             --cluster your-cluster-name
#             --service your-service-name
#             --force-new-deployment
